**Q10. Data Transformation for Model Input (NumPy)**

**Context: ML models require structured numeric arrays.**

Tasks:

1. Create two arrays of shape (3,2)
2. Perform: Vertical stacking Horizontal stacking
3. Reshape into (2,6)
4. Explain: Why reshaping is required in ML pipelines

In [3]:
#Create two arrays of shape (3,2)

import numpy as np

# First array (3 rows, 2 columns)
X1 = np.array([1, 2],[3, 4],[5, 6]])

# Second array (3 rows, 2 columns)
X2 = np.array([[7, 8],[9, 10],[11, 12]])

print(X1.shape)  # (3, 2)
print(X2.shape)  # (3, 2)

(3, 2)
(3, 2)


In [6]:
#Perform: Vertical stacking Horizontal stacking
import numpy as np

array1 = np.array([[1, 2], [3, 4],[5, 6]])

array2 = np.array([[7, 8],[9, 10],[11, 12]])
verticalStack = np.vstack((array1, array2))
print(verticalStack)
print(verticalStack.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)


In [12]:
#3. Reshape into (2,6)
import numpy as np

array1 = np.array([[1, 2], [3, 4],[5, 6]])

array2 = np.array([[7, 8],[9, 10],[11, 12]])
verticalStack = np.vstack((array1, array2))

reshapedArray = verticalStack.reshape(2, 6)

print(reshapedArray)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#4. Explain: Why reshaping is required in ML pipelines
Reshaping ensures that numerical data is structured correctly so machine learning models can process it without errors.